### PR TITLE
Fix: Adds support for Visua11y's 'no animations' option (fixes #3)

### LINKED ISSUE #3: Visua11y no animation support
Issue:
Ability to turn off animation and show end frame

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #3 

### Fix
* Adds support for Visua11y's "no animations" option. Requires framework **v5.31.27** due to the DOM Element Modification API dependency
* Fixes issue when using `"_playFirstViewOnly": true` and scrolling off and back again. The frame displayed when back on screen was blank. May not be an issue (see notes).

### Notes
For some reason, I needed to subtract one from the total frames in order to go to the last frame.

```
this.animation.totalFrames - 1
```

This was causing an issue with `_playFirstViewOnly` which has been fixed. It would be good to know if the problem was with the specific `.svgz` [file](https://lottiefiles.com/animations/cube-shape-animation-k69Xropjds) that I was using, or if others can reproduce the same issue.

In any case, would it be safer to just stop at the 2nd to last frame in case any given `.svgz` file has the same issue? I don't know how often this issue comes up.

### CODE REVIEW

File: js/LottieView.js [hunk 1]
```diff
@@ -140,6 +140,10 @@ export default class LottieView extends Backbone.View {
   setUpListeners() {
     this.$el.on('onscreen', this.onScreenChange);
     this.listenTo(Adapt, 'device:resize', this.render);
+
+    documentModifications.on('changed:html', event => {
+      this.checkVisua11y();
+    });
```
Comment (oliverfoster) [inline js/LottieView.js:146]:
```suggestion
    this.checkVisua11y = this.checkVisua11y.bind(this);
    documentModifications.on('changed:html', this.checkVisua11y);
```

File: js/LottieView.js [hunk 2]
```diff
@@ -254,6 +262,14 @@ export default class LottieView extends Backbone.View {
     if (this.hasUserPaused && this.config._onPauseRewind) this.rewind();
   }
 
+  checkVisua11y() {
+    const htmlClasses = document.documentElement.classList;
+    if (!htmlClasses.contains('a11y-no-animations')) return;
+
+    // Stop on last frame
+    this.goToEndAndStop();
```
Comment (oliverfoster) [inline js/LottieView.js:270]: Probably need to deal with what happens if the person unticks `no animations`?

Comment (swashbuck) [reply js/LottieView.js:288]: Done. It should now replay and will reshow the play/pause controls based on the initial config value.

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
Beautiful. So easy to read. Thanks.
